### PR TITLE
Add command arguments

### PR DESCRIPTION
**Pull request by ryo33**
### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

I added `command-arguments` which allows to pass `--config path-to/deny.toml`.

### CODE REVIEW

**Comment by ryo33** [comment]
https://github.com/Hihaheho/Desk/runs/6262403080?check_suite_focus=true#step:6:1
This works.

**Comment by Jake-Shadle** [comment]
Sorry I haven't gotten to this yet, I'm actually not sure how I feel about this change, as the same can be accomplished already by just setting `command` to eg `check --config path-to/deny.toml`.

**Comment by ryo33** [comment]
In your logic, I think `arguments` is also not needed because `command` can include arguments eg `--all-features check --config path-to/deny.toml`. There is `arguments` and `command`, so it is confusing that `arguments` cannot have `--config` or something and `command` can. The name `command` does not imply it can includes command arguments. I think we should change something, but I don't have any idea yet.

**Comment by Jake-Shadle** [comment]
That was mainly due to us adding `--all-features` in a backwards compatible way since that was not in the initial versions, but is what most users expect to happen, but I get your point.

**Review by Jake-Shadle — COMMENTED** [review]
But that being said, this doesn't negatively impact the action so I'm fine merging it.

**Comment by ryo33** [comment]
Thanks! I hope this helps someone.

**Pull request merged**
