### PR TITLE
feat: Speed up consecutive builds by 330%

### LINKED ISSUE #3: Reduce image size with alpine as base
Wanted to use alpine as as a docker image base, but as `cargo-deny` requires Cargo to be installed (due to `cargo_metadata` crate that runs the `cargo` command) I'm simply using the Rust debian image as base now instead.

If `cargo-deny` would support linking in Cargo then it would be fully standalone and using alpine would be easy, tracked in https://github.com/EmbarkStudios/cargo-deny/issues/54

May also be able to switch to alpine and just install Cargo to it and the minimal dependencies needed

### LINKED ISSUE #4: Pre-built docker image?
Looks like it takes around 1 min for GitHub ([example](https://github.com/embarkStudios/texture-synthesis/commit/42932ea6051fcd8fca15485d9bb7fb1f99e7eba4/checks?check_suite_id=358551545)) to build the current docker image that we use, and even more importantly; it does it every time for every repo that uses this action - which is not ideal.

Would have expected GitHub to cache that if it is from the same version or revision of an action, maybe that is not implemented yet?

What we could do however is to build and publish a docker image from this repo and refer to that instead in the action. Requires a bit more set up however when versioning, but should be doable. Alternatively can have the `cargo-deny` repo itself build and publish the images and simply just use the right one here in the action, that is likely the cleanest

### PR DESCRIPTION
**Pull request by jacobsvante**
This is done by moving to a composite action and utilizing Swatinem's wonderful GitHub action [rust-cache](https://github.com/Swatinem/rust-cache).

Closes #3
Closes #4 

### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

Move to a composite based Github Action.

### Related Issues

#3
#4

### CODE REVIEW

**Review by repi — CHANGES_REQUESTED** [review]
That's a good speed up! 

Though I don't think we can accept this change due to additional supply chain security concerns, this makes this action dependent on 3 other actions created by 3 other users/groups - but we want this action to be standalone for easy review and so you just need to trust the simple code in this (and be able to fork it / pin it to lock down exact version) which is not possible if it depends on 3 other actions

**Comment by jacobsvante** [comment]
Hej Johan!

Gotcha.

What about freezing each action to a specific commit? And providing static code in place of Swatinem/rust-cache? The other two actions are basically the de-facto standard when combining GitHub Actions with Rust.

**Comment by Jake-Shadle** [comment]
This is also problematic because it installs cargo-deny from source, making the action version pointless and making it so users can't pin to a specific version, which is kind of how the v1 tag works currently since we bump it with every new release, but it takes away the ability for a user to opt out of that behavior.

**Comment by jacobsvante** [comment]
Hi @Jake-Shadle,

Well isn't that easily fixed by adding `@0.12.2`? One could also allow an override via the action's inputs.

**Review by Jake-Shadle — COMMENTED** [review]
Looking at this pr now seems like you have done your own fork/release so don't see the need to keep this open.

**Comment by jacobsvante** [comment]
Sounds good. Considering your supply chain concerns I think it's reasonable to close the PR (I forgot that I left it open).

**Pull request closed without merging**
