### PR TITLE
Bump rust to 1.60

### PR DESCRIPTION
**Pull request by MarcoIeni**
### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

This action is failing in my [project](https://github.com/MarcoIeni/release-plz) due to an [issue](https://github.com/rust-lang/cargo/issues/10623) with an old cargo version.

Can you release a new version of the action with an updated rust toolchain? :pray:

### CODE REVIEW

**Comment by Jake-Shadle** [comment]
The `rust-version` argument was explicitly added for this situation, can you not use that?

**Comment by MarcoIeni** [comment]
yes, I noticed this after opening this PR. I will use that. Any reason why you don't want to use rust 1.60?

**Comment by Jake-Shadle** [comment]
In this case it's not a big deal, but `rust-version` was added so that anyone could essentially unblock themselves rather than rely on getting a PR on this repo merged and released.

**Comment by MarcoIeni** [comment]
I am now using this argument in my project, thanks! Feel free to merge or close this PR :)

**Review by Jake-Shadle — APPROVED** [review]

**Pull request merged**
